### ISSUE TITLE
Question about Training Step 3. Create picked_faces.obj (optional)

### ISSUE THREAD

**Issue by RuihanGao** [yihua7/NeRF-Texture#2]
I am trying to reproduce the results synthesizing durian's 3D texture and copy it to the banana. 
For Step 3, I can select the bottom region using "rectangle selection" tool in MeshLab, but how shall I cut it afterwards? I tried "delete selected faces and vertices", but it is not a closed mesh object for saving.
![Screenshot from 2023-06-13 21-00-09](https://github.com/yihua7/NeRF-Texture/assets/33533196/0d495f87-af83-486b-93bb-19b0e8c70d17)
![Screenshot from 2023-06-13 21-17-19](https://github.com/yihua7/NeRF-Texture/assets/33533196/73fc82c7-6be9-4026-b076-07a4c1bc3976)

If skipping this step, I could get synthesized texture, but not uniform as demonstrated.

![Screenshot from 2023-06-13 21-36-44](https://github.com/yihua7/NeRF-Texture/assets/33533196/95e9e27a-65b3-4ac5-91ee-8861727ce200)
![Screenshot from 2023-06-13 21-39-51](https://github.com/yihua7/NeRF-Texture/assets/33533196/13d0d65b-9ae9-4876-a41d-ffb302fdd815)

### ps: I reproduce the above results using `--tcnn` flag instead of `--ff` flag, as I was unable to install `ffmlp` package. 
Do you have any suggestion on that?

**Comment by yihua7** [comment]
The file picked_faces.obj does not necessarily need to be a closed mesh. It serves as a template on which implicit patches are sampled from. In the specific 'durian' scene, only the upper portion of the fruit is visible, while the lower part is occluded by the platform supporting it. Without having constructed a picked_faces.obj file, the texture synthesis process will use the lower region that cannot be seen and this can lead to a noisy or imperfect result. To avoid this, please consult the picked_faces.obj model included in the data provided in the Quick Start guide.
