### ISSUE TITLE
Using NeRF-Texture to reconstruct photorealistic portrait 

### ISSUE THREAD

**Issue by oijoijcoiejoijce** [yihua7/NeRF-Texture#3]
Love the paper - super cool approach. How would you use this to reconstruct photorealistic portrait? (They gave example of this in an older paper - Deferred Neural Rendering: Image Synthesis using Neural Textures)

**Comment by yihua7** [comment]
Thank you for your attention! This paper synthesizes textures in a scheme of Markov random process, focusing mainly on static and local textures like grass, rather than global and high-level-semantic textures like faces.
