### ISSUE TITLE
Confused about the "intersections" for texture synthesis

### ISSUE THREAD

**Issue by RuihanGao** [yihua7/NeRF-Texture#5]
Sec 3.2.1 of the paper mentions, "we place square scan arrays of 128 × 128 resolution on each tangent plane of the coarse mesh to obtain the intersections of the scanning rays with the _**mesh**_. "
Does the last "_**mesh**_" refers to the coarse mesh or the fine mesh with meso-structure?

As far as I understand, the implementation is [this part](https://github.com/yihua7/NeRF-Texture/blob/14e2bcd6676026216ee8295212bb4205cdab9c18/tools/map.py#L1082). The variable "intersections" is used for knn search, so sounds like the points on the fine mesh. However, it is obtained by the ray-tracing from scan rays to the coarse mesh. 

Did I misunderstand something?

**Comment by yihua7** [comment]
- "Mesh" refers to the coarse mesh, on which latent features locate.
- "intersections" on the coarse mesh can be directly utilized to fetch latent features as shown in [here](https://github.com/yihua7/NeRF-Texture/blob/14e2bcd6676026216ee8295212bb4205cdab9c18/tools/map.py#L1087).
