### ISSUE TITLE
The issue about training on my own datasets

### ISSUE THREAD

**Issue by HarshWinterBytes** [yihua7/NeRF-Texture#7]
Hearty congratulations for presenting such an excellent job! 
When I test on my own datasets, I have three problems: 
1. The download speed of Baidu cloud is really slow, can you put the example dataset on Google cloud or Ali cloud? It would help a lot. 
2. I have a apple dataset which include 66 imges with resolution of 3000 × 4000 × 4（RGBA）and have been tested successfully on openmvs and Instant-NGP. And I run the coarse shape estimation with command:
`CUDA_VISIBLE_DEVICES=0 python main_nerf.py ./data/apple --workspace ./logs/apple -O --bound 1.0 --scale 0.8 --dt_gamma 0 --ff --mode colmap --gui` 
But when I click on the 'save_pcl' button to extract scan point cloud, the terminal gives a error messages: **failed to save ply (the number of vertex is 0).**
And when I open the ngp_1.obj, the meshlab also gives a error: **No vertex found.**
3. I train a fox dataset which is come from Instant-NGP. This time it is fine to do the coarse shape estimation. But another problem arises: 
The program is stuck at **'calculating H threshold...'**, more specifically at line **148** in **main.py**:
 `udf = np.abs(trimesh.proximity.ProximityQuery(surface_mesh).signed_distance(scanned_ply))`.
And eventually the program will crash.
By monitoring the CPU and GPU, I found that its direct reason is the memory (64GB) is fully occupied. The size of pcl.ply is 15.8MB.

**My environment:**
**OS:** Ubuntu 22.04
**Python:** 3.10.12
**CUDA:** 11.3
**pytorch:** 1.12.1
**pytorch3d:** 0.7.4

Looking for you early reply. Best wishes!

**Comment by yihua7** [comment]
Hi,
1. Currently I do not have Google and Ali cloud accounts. So sorry for the inconvenience caused. :(
2. Did you click the 'train' button and wait until the convergence? Did the training results of NGP look good? It seems that the whole space was empty when you clicked the 'save_pcl', which resulted in that Marching Cubes (save_mesh) and depth estimation (save_pcl) both obtain empty files. 
3. To reduce the size of pcl.ply, please feel free to reduce the value of K (=16 by default) in [here](https://github.com/yihua7/NeRF-Texture/blob/14e2bcd6676026216ee8295212bb4205cdab9c18/nerf/utils.py#L1102). For face-forward scenes, I suggest a smaller view covering (e.g K=3 or 4). Besides, raise the voxel_size when downsampling the point cloud in [here](https://github.com/yihua7/NeRF-Texture/blob/14e2bcd6676026216ee8295212bb4205cdab9c18/nerf/utils.py#L1146l) is another choice.

**Comment by HarshWinterBytes** [comment]
> Hi,
> 
> 1. Currently I do not have Google and Ali cloud accounts. So sorry for the inconvenience caused. :(
> 2. Did you click the 'train' button and wait until the convergence? Did the training results of NGP look good? It seems that the whole space was empty when you clicked the 'save_pcl', which resulted in that Marching Cubes (save_mesh) and depth estimation (save_pcl) both obtain empty files.
> 3. To reduce the size of pcl.ply, please feel free to reduce the value of K (=16 by default) in [here](https://github.com/yihua7/NeRF-Texture/blob/14e2bcd6676026216ee8295212bb4205cdab9c18/nerf/utils.py#L1102). For face-forward scenes, I suggest a smaller view covering (e.g K=3 or 4). Besides, raise the voxel_size when downsampling the point cloud in [here](https://github.com/yihua7/NeRF-Texture/blob/14e2bcd6676026216ee8295212bb4205cdab9c18/nerf/utils.py#L1146l) is another choice.

Thank you for your quick reply! It helps a lot!
